// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ5F4hYuTl2YJi987coe2QNc40FIgzLg0',
    appId: '1:814069529758:web:44454a35eeed2f51bdcf8f',
    messagingSenderId: '814069529758',
    projectId: 'ui275-dd1cf',
    authDomain: 'ui275-dd1cf.firebaseapp.com',
    storageBucket: 'ui275-dd1cf.appspot.com',
    measurementId: 'G-7CBXF3CBBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_EOPrGh19E0AA5JF72Cmynj00tjRYFo0',
    appId: '1:814069529758:android:236142352c323523bdcf8f',
    messagingSenderId: '814069529758',
    projectId: 'ui275-dd1cf',
    storageBucket: 'ui275-dd1cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8lJ6bWy0rpyiRxgQEAGxWefh5pXPLBzE',
    appId: '1:814069529758:ios:d2096a046c3a2c1ebdcf8f',
    messagingSenderId: '814069529758',
    projectId: 'ui275-dd1cf',
    storageBucket: 'ui275-dd1cf.appspot.com',
    iosBundleId: 'com.example.practiceUi27',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8lJ6bWy0rpyiRxgQEAGxWefh5pXPLBzE',
    appId: '1:814069529758:ios:d2096a046c3a2c1ebdcf8f',
    messagingSenderId: '814069529758',
    projectId: 'ui275-dd1cf',
    storageBucket: 'ui275-dd1cf.appspot.com',
    iosBundleId: 'com.example.practiceUi27',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ5F4hYuTl2YJi987coe2QNc40FIgzLg0',
    appId: '1:814069529758:web:0486720ccaa42ae0bdcf8f',
    messagingSenderId: '814069529758',
    projectId: 'ui275-dd1cf',
    authDomain: 'ui275-dd1cf.firebaseapp.com',
    storageBucket: 'ui275-dd1cf.appspot.com',
    measurementId: 'G-BV3VNSGFNX',
  );
}
